// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoOutputPath(arg1:string):Promise<string>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAvailableEncoders():Promise<Array<main.EncoderInfo>>;

export function GetVideoInfo(arg1:string):Promise<main.VideoInfo>;

export function OpenVideoFile():Promise<string>;

export function SaveOutputFile(arg1:string):Promise<string>;

export function TrimVideo(arg1:main.TrimParams):Promise<main.TrimResult>;
