// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoOutputPath(arg1) {
  return window['go']['main']['App']['AutoOutputPath'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetAvailableEncoders() {
  return window['go']['main']['App']['GetAvailableEncoders']();
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function OpenVideoFile() {
  return window['go']['main']['App']['OpenVideoFile']();
}

export function SaveOutputFile(arg1) {
  return window['go']['main']['App']['SaveOutputFile'](arg1);
}

export function TrimVideo(arg1) {
  return window['go']['main']['App']['TrimVideo'](arg1);
}
